Develop contact section
zainsadaqat/portfolio pull request #3
Opened 2021-07-13 21:38 UTC by zainsadaqat

# Develop Contact Section with HTML Forms

The form includes the following fields:
* Full Name
* Email
* Message
* Submit Button

2021-07-14 00:16 UTC, george-swift requested changes
### Status: Changes Required 🔔 

Hello Zain 👋🏽 ,

Good job so far! 👏🏽 👏🏽  You have implemented some of the basic requirements for this project. Your form looks great!  Before the next project, however, there are some issues you need to work on. But you are almost there! 🚀 

## Required Changes ♻️
### _Check the comments under the review._ 👇🏽 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏🏽 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-14 00:16 UTC, george-swift commented on index.html
> +            ></textarea>
- [x] You integrated with the Formspree service correctly. However, the data entered into a form needs to be in the right format and certain fields need to be filled in order to effectively use the submitted form. Currently, only the name input field is `required`. Kindly add the `required` attribute to the `email` and `textarea` elements. All three fields are required for server processing.

2021-07-14 00:16 UTC, george-swift commented on index.html
> +          </li>
- [x] The button submits the form 👍🏽 but buttons are multi-state objects and it's very important for users to get some visual feedback for a given interaction. The Figma template provided styling rules for `hover`, `active (when it's pressed)`, and `enabled (default state)`. Kindly implement this requirement.

2021-07-14 00:16 UTC, george-swift commented on style.css
> +  font-weight: 600;
[OPTIONAL]
- [ ] The form implements flexbox correctly 👏🏽 . However, it's also important for its elements to adhere to the font style and weight from Figma as much as possible. It'll improve user experience as well.

2021-07-14 12:06 UTC, Emmyn5600 approved these changes
## STATUS: APPROVED :muscle::clap:

Hi, @zainsadaqat 

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous code reviewer.

May I highlight the following:
- The repo looks professional:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have a descriptive PR:heavy_check_mark:
- Your contact form is working properly:heavy_check_mark:

## Optional suggestion
  * Kindly, include the live link demo in your Readme file.

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-14 12:12 UTC, merged

2022-01-22 11:24 UTC, zainsadaqat commented on index.html
> +            ></textarea>
Alright man

2022-01-22 11:26 UTC, zainsadaqat commented
# Thank you, @Emmyn5600 for approving this pull request, and @george-swift for your useful tips and suggestions!

<img src="https://media1.giphy.com/media/ukJ4Gueb2QgUHcvjro/giphy.gif"/>